<?php
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_field().
 */


function lei_views_pre_render(ViewExecutable $view) {
  \Drupal::logger('lei')->info('View name1: @view_name', ['@view_name' => $view->storage->id()]);
  if (isset($view) && ($view->storage->id() == 'frontpage')) {
    $view->element['#attached']['library'][] = 'lei/lei_styles';

    if (isset($view->result) && is_array($view->result)) {
      foreach ($view->result as &$row) {
        
        // Check if the LEI status field exists in the row.
        if (isset($row->_entity) && $row->_entity->hasField('field_lei_status')) {
          $status = $row->_entity->get('field_lei_status')->value;
          \Drupal::logger('lei')->info('View name1: @view_name', ['@view_name' => $status]);
          // Define the CSS class based on the status value.
          switch ($status) {
            case 'ISSUED':
              $row->field_lei_status_class = 'lei-status-issued';
              break;
          
            case 'LAPSED':
              $row->field_lei_status_class = 'lei-status-lapsed';
              break;
          
            default:
              $row->field_lei_status_class = 'lei-status-unknown';
              break;
          }          
        }
      }
    }
  }
} 


  /*function lei_preprocess_views_view(&$variables) {
    $view = $variables['view']; 

    //\Drupal::logger('lei')->info('View name1: @view_name', ['@view_name' => $variables['view']->name]);
    // Replace 'your_view_name' with the machine name of your view.
    $variables['#attached']['library'][] = 'lei0/lei_styles';
  }

function lei_preprocess_field(&$variables) {
    // Check if the field is from the specific view and the target field.
    \Drupal::logger('lei')->info('View name2: @view_name', ['@view_name' => $view_name]);

    if (isset($variables['#view']) && $variables['#view']->name == 'frontpage' && $variables['#field_name'] == 'field_lei_status') {
      $field_value = $variables['#items'][0]['#markup']; // Assuming single value field.
      
      // Add CSS classes based on field value.
      if ($field_value == 'ISSUED') {
        $variables['#attributes']['class'][] = 'lei-status-issued';
      }
      elseif ($field_value == 'LAPSED') {
        $variables['#attributes']['class'][] = 'lei-status-lapsed';
      }
      else {
        $variables['#attributes']['class'][] = 'lei-status-other';
      }
    }
  }*/